# Generated by Django 3.0.7 on 2020-06-28 21:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_contributed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+12125552368', max_length=128, region=None)),
                ('inshuro', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('PR', 'President'), ('VP', 'Vice President'), ('CO', 'Comptable'), ('UM', 'Umwanditsi'), ('JY', 'Umujyanama'), ('MB', 'Normal Member')], default='MB', max_length=2)),
                ('member_image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('contributions', models.ManyToManyField(default=1, to='ubumwe_app.Contribution')),
            ],
        ),
    ]
