# Generated by Django 3.0.7 on 2020-06-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubumwe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='contributions',
            field=models.ManyToManyField(to='ubumwe_app.Contribution'),
        ),
    ]
