# Generated by Django 3.0.7 on 2020-06-28 14:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ubumwe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+12125552368', max_length=128, region=None),
        ),
    ]
