# Generated by Django 3.0.7 on 2020-06-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubumwe_app', '0002_auto_20200628_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='asigayemo',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
