# Generated by Django 3.0.7 on 2020-06-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubumwe_app', '0002_auto_20200628_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
