# Generated by Django 3.0.7 on 2020-06-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubumwe_app', '0003_contribution_asigayemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_borrowed', models.DateTimeField()),
                ('abishingizi', models.ManyToManyField(to='ubumwe_app.Member')),
            ],
        ),
    ]
