# Generated by Django 3.0.7 on 2020-06-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubumwe_app', '0005_loan_yarishyuwe'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='loans',
            field=models.ManyToManyField(to='ubumwe_app.Loan'),
        ),
    ]
