# Generated by Django 3.0.7 on 2020-06-28 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubumwe_app', '0005_auto_20200628_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='contributions',
            field=models.ManyToManyField(related_name='contributions', to='ubumwe_app.Contribution'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubumwe_app.Member'),
        ),
    ]
