# Generated by Django 3.0.7 on 2020-06-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubumwe_app', '0006_member_loans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='abishingizi',
            field=models.ManyToManyField(blank=True, to='ubumwe_app.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='loans',
            field=models.ManyToManyField(blank=True, to='ubumwe_app.Loan'),
        ),
    ]
