# Generated by Django 3.0.7 on 2020-06-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubumwe_app', '0006_auto_20200628_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='contributions',
            field=models.ManyToManyField(related_name='members', to='ubumwe_app.Contribution'),
        ),
    ]
