# Generated by Django 3.0.7 on 2020-06-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubumwe_app', '0007_auto_20200701_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='contributions',
            field=models.ManyToManyField(blank=True, to='ubumwe_app.Contribution'),
        ),
    ]
